pipeline {
  agent {
    kubernetes {
      //cloud 'kubernetes'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:1.11
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
    }
  }
  stages {
    stage('Build Docker image') {
      steps {
        git 'https://github.com/alex-y-kozlov-sandbox/jenkins-pipeline-demos.git'
        container('docker') {
                script {
                def image = docker.build("ykpersonal/jenkins-test:0.1","m4")
                image.inside(){
                  sh "docker info"
                }
            }
         }
      }
    }
  }
}
